blast_settings:
    blast_location:
    blast_e: 1e-20
    blast_b: 20000000
    blast_v: 20000000
trf_settings:
    trf_match: 2
    trf_mismatch: 5
    trf_indel: 7
    trf_p: 80
    trf_q: 10
    trf_threshold: 50
    trf_length: 2000
    trf_param_postfix: 2.5.7.80.10.50.2000
    trf_masked_file: False
    trf_flanked_data: True
    trf_data_file: True
    trf_nohtml: True
    overlapping_cutoff: 10
    overlapping_cutoff_proc: 30
    overlapping_gc_diff: 0.05
jellyfish_settings:
    threads: 30
    hash_size: 10G
    hash_bits: 10
    both_strands: "--both-strands"
    both_strands_new: "--canonical"
ngrams_settings:
    ngram_length: 23
    ngram_m: 10000000
